apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mern-app

resources:
  - namespace.yaml   # Remove this if namespace already exists
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
